apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: LLMInferenceService
      name: model
    patch: |-
      - op: replace
        path: /metadata/name
        value: qwen
      - op: replace
        path: /spec/model/uri
        value: "hf://Qwen/Qwen3-4B"
      - op: replace
        path: /spec/model/name
        value: "Qwen/Qwen3-4B"
