apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: vllm
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
spec:
  predictor:
    automountServiceAccountToken: false
    maxReplicas: 3
    minReplicas: 3
    model:
      modelFormat:
        name: vLLM
      name: ''
      resources:
        limits:
          cpu: '4'
          memory: 16Gi
          nvidia.com/mig-3g.71gb: '1'
        requests:
          cpu: '4'
          memory: 16Gi
          nvidia.com/mig-3g.71gb: '1'
      runtime: vllm-runtime
      storageUri: ''
    tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
